service: emailrecognotion
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - 's3:*'
            - rekognition:DetectText
resources: 
  Resources:
    BilguunBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: zorigoobilguunleap3emaildetection
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - POST
              AllowedOrigins:
                - '*'
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref BilguunBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - arn:aws:s3:::zorigoobilguunleap3emaildetection/*
              Effect: Allow
              Principal: "*"

functions:
  uploadImage:
    handler: index.uploadImage
    events:
      - http:
          path: /
          method: POST
          cors: true
  detectEmail:
    handler: index.detectEmail
    events:
      - http:
          path: /
          method: GET
          cors: true
      - s3:
          bucket: zorigoobilguunleap3emaildetection
          event: s3:ObjectCreated:*
          existing: true
    
