service: emailsign
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action: "lambda:InvokeFunction"
        - Effect: "Allow"
          Resource: "*"
          Action:
          - 'dynamodb:*'

functions:
  signup:
    handler: index.signup
    events:
      - http: POST signup
  signin:
    handler: index.signin
    events:
      - http: POST signin