service: triggerlambdabys3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

resources: 
  Resources:
    BilguunBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: zorigoobilguunleap3triggers3
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref BilguunBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - arn:aws:s3:::zorigoobilguunleap3triggers3/*
              Effect: Allow
              Principal: "*"
functions:
  function1:
    handler: index.get_s3_upload_url
  function2:
    handler: index.function_will_be_triggerd_by_s3
    events:
      - s3:
          bucket: zorigoobilguunleap3triggers3
          event: s3:ObjectCreated:*
          existing: true
