service: triggerlambdabys3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action: 
            - 's3:*'

resources: 
  Resources:
    BilguunBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: zorigoobilguunleap3triggers3
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - POST
              AllowedOrigins:
                - '*'
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref BilguunBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - arn:aws:s3:::zorigoobilguunleap3triggers3/*
              Effect: Allow
              Principal: "*"
functions:
  function1:
    handler: index.get_s3_upload_url
    events:
      - http: 
          path: /
          method: POST
          cors: true
  function2:
    handler: index.getPhotos
    events:
      - http:
          path: /
          method: GET
          cors: true
      - s3:
          bucket: zorigoobilguunleap3triggers3
          event: s3:ObjectCreated:*
          existing: true
